# Generated by Django 4.1.7 on 2023-03-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('imgurl', models.CharField(max_length=400)),
                ('product_description', models.TextField()),
            ],
        ),
    ]
