# Generated by Django 4.1.7 on 2023-03-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cartinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartInfo',
        ),
    ]
